### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by anchxng** [AkeBoss-tech/GuessingGame#1]
you wrote "twelcome to guessing game"
change to "welcome to guessing game"

**Comment by AkeBoss-tech** [comment]
ok I will fix it

**Comment by AkeBoss-tech** [comment]
Wait a second, this isn't a typo. The '\t' is a tab function, just like how '\n' makes a new line. The reason why I have the tab there is to center it.

**Comment by anchxng** [comment]
oh
